export const DEFAULT_TIME_INTERVAL = 5;
export const DEFAULT_INVITES_LIMIT = 100;

export const SEARCH_URL = 'https://www.linkedin.com/search/results/people/?origin=GLOBAL_SEARCH_HEADER';

export const FIRST_CIRCLE_CONNECTIONS_TYPE = 'F';
export const SECOND_CIRCLE_CONNECTIONS_TYPE = 'S';
export const THIRD_CIRCLE_CONNECTIONS_TYPE = 'O';

export const PORT_NAME_POPUP = 'PORT_NAME_POPUP';
export const PORT_NAME_BACKGROUND = 'PORT_NAME_BACKGROUND';

export const MESSAGE_GET_SETTINGS = 'MESSAGE_GET_SETTINGS';
export const MESSAGE_LOGGED_IN  = 'MESSAGE_LOGGED_IN';
export const MESSAGE_NOT_LOGGED_IN = 'MESSAGE_NOT_LOGGED_IN';
export const MESSAGE_SAVE_NEW_INVITE = 'MESSAGE_SAVE_NEW_INVITE';
export const MESSAGE_CHECK_IF_CURRENT_TAB = 'MESSAGE_CHECK_IF_CURRENT_TAB';
export const MESSAGE_UPDATE_INVITE_COUNTER = 'MESSAGE_UPDATE_INVITE_COUNTER';
export const MESSAGE_CLOSE_CURRENT_SESSION = 'MESSAGE_CLOSE_CURRENT_SESSION';
export const MESSAGE_SEND_FOUND_CONTACTS_AMOUNT = 'MESSAGE_SEND_FOUND_CONTACTS_AMOUNT';
export const MESSAGE_REQUEST_FOUND_CONTACTS_AMOUNT = 'MESSAGE_REQUEST_FOUND_CONTACTS_AMOUNT';

export const ERROR_NOT_LOGGED_IN = 'ERROR_NOT_LOGGED_IN';

export const DAY_MS = 24 * 60 * 60 * 1000;
