export const DEFAULT_TIME_INTERVAL = 5;
export const DEFAULT_INVITES_LIMIT = 100;

export const SEARCH_URL
  = 'https://www.linkedin.com/search/results/people/?facetNetwork=%5B"S"%2C"O"%5D&keywords=&origin=GLOBAL_SEARCH_HEADER';

export const PORT_NAME_POPUP = 'PORT_NAME_POPUP';
export const PORT_NAME_BACKGROUND = 'PORT_NAME_BACKGROUND';

export const MESSAGE_GET_SETTINGS = 'MESSAGE_GET_SETTINGS';
export const MESSAGE_LOGGED_IN  = 'MESSAGE_LOGGED_IN';
export const MESSAGE_NOT_LOGGED_IN = 'MESSAGE_NOT_LOGGED_IN';
export const MESSAGE_SAVE_NEW_INVITE = 'MESSAGE_SAVE_NEW_INVITE';
export const MESSAGE_CHECK_IF_CURRENT_TAB = 'MESSAGE_CHECK_IF_CURRENT_TAB';
export const MESSAGE_UPDATE_INVITE_COUNTER = 'MESSAGE_UPDATE_INVITE_COUNTER';

export const ERROR_NOT_LOGGED_IN = 'ERROR_NOT_LOGGED_IN';

export const DAY_MS = 24 * 60 * 60 * 1000;
